def user_lives (num_live):
    if num_live == 6:
        print(   '                      '   )
        print(   '        _______       '   )
        print(   '       |       |      '   )
        print(   '               |      '   )
        print(   '               |      '   )
        print(   '               |      '   )
        print(   '               |      '   )
        print(   '               |      '   )
        print(   '               |      '   )
        print(   '               |      '   )
        print(   '          _____|      '   )
        print(   '                      '   )

    if num_live == 5:
        print(   '                      '   )
        print(   '        _______       '   )
        print(   '       |       |      '   )
        print(   '      ( )      |      '   )
        print(   '               |      '   )
        print(   '               |      '   )
        print(   '               |      '   )
        print(   '               |      '   )
        print(   '               |      '   )
        print(   '               |      '   )
        print(   '          _____|      '   )
        print(   '                      '   )

    if num_live == 4:
        print(   '                      '   )
        print(   '        _______       '   )
        print(   '       |       |      '   )
        print(   '      ( )      |      '   )
        print(   '       |       |      '   )
        print(   '       |       |      '   )
        print(   '               |      '   )
        print(   '               |      '   )
        print(   '               |      '   )
        print(   '               |      '   )
        print(   '          _____|      '   )
        print(   '                      '   )

    if num_live == 3:
        print(   '                      '   )
        print(   '        _______       '   )
        print(   '       |       |      '   )
        print(   '      ( )      |      '   )
        print(   '       |       |      '   )
        print(   '     --|       |      '   )
        print(   '               |      '   )
        print(   '               |      '   )
        print(   '               |      '   )
        print(   '               |      '   )
        print(   '          _____|      '   )
        print(   '                      '   )

    if num_live == 2:

        print(   '                      '   )
        print(   '        _______       '   )
        print(   '       |       |      '   )
        print(   '      ( )      |      '   )
        print(   '       |       |      '   )
        print(   '     --|--     |      '   )
        print(   '               |      '   )
        print(   '               |      '   )
        print(   '               |      '   )
        print(   '               |      '   )
        print(   '          _____|      '   )
        print(   '                      '   )

    if num_live == 1:

        print(   '                      '   )
        print(   '        _______       '   )
        print(   '       |       |      '   )
        print(   '      ( )      |      '   )
        print(   '       |       |      '   )
        print(   '     --|--     |      '   )
        print(   '      /        |      '   )
        print(   '     /         |      '   )
        print(   '               |      '   )
        print(   '               |      '   )
        print(   '          _____|      '   )
        print(   '                      '   )
        print(   '    ONE LAST TRY!     '   )

    if (num_live == 0):

        print(   '                      '   )
        print(   '        _______       '   )
        print(   '       |       |      '   )
        print(   '      ( )      |      '   )
        print(   '       |       |      '   )
        print(   '     --|--     |      '   )
        print(   '      / \\      |      '   )
        print(   '     /   \\     |      '   )
        print(   '               |      '   )
        print(   '               |      '   )
        print(   '          _____|      '   )
        print(   '                      '   )